language: cpp
compiler: clang
sudo: required
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - libstdc++6
      - libstdc++-7-dev
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

before_install:
  # Install a supported cmake version (>= 3.11)
  - wget -O cmake.sh https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

  # Install Vulkan SDK
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - export CXX="clang++-6.0" CC="clang-6.0"
  - git clone https://github.com/KhronosGroup/Vulkan-Headers.git $TRAVIS_BUILD_DIR/../Vulkan-Headers
  - cd $TRAVIS_BUILD_DIR/../Vulkan-Headers
  - git checkout c4e056d365472174471a243dfefbfe66a03564af
  - git clone https://github.com/KhronosGroup/Vulkan-Hpp.git $TRAVIS_BUILD_DIR/../Vulkan-Hpp
  - cd $TRAVIS_BUILD_DIR/../Vulkan-Hpp
  - git checkout 7e701c79d6998260712dc6578732d534871f0f8a
  - mkdir -p $TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/x86_64/
  - mkdir -p $TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/Include/
  - cp $TRAVIS_BUILD_DIR/../Vulkan-Headers/include $TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/Include/
  - cp $TRAVIS_BUILD_DIR/../Vulkan-Hpp/include $TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/Include/
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/x86_64
  - export VK_VERSION=1.1.82.1

script:
  - bash build.sh -VULKAN_VERSION 1.1.82.1 -VULKAN_ROOT $TRAVIS_BUILD_DIR/../VulkanSDK -COMPILER CLang -G Make