language: cpp
compiler: clang
sudo: required
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - libstdc++6
      - libstdc++-7-dev
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

before_install:
  # Install a supported cmake version (>= 3.11)
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget -O cmake.sh https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh
  - chmod +x cmake.sh
  - ./cmake.sh --prefix=$HOME/usr --exclude-subdir --skip-license

  # Install Vulkan SDK
  - mkdir -p $TRAVIS_BUILD_DIR/../VulkanSDK
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - export VK_VERSION=1.1.82.1
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz -C $TRAVIS_BUILD_DIR/../VulkanSDK
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/x86_64
  - export CXX="clang++-6.0" CC="clang-6.0"
  

script:
  - bash build.sh -VULKAN_VERSION 1.1.82.1 -VULKAN_ROOT $TRAVIS_BUILD_DIR/../VulkanSDK -COMPILER CLang -G Make -cmake_params "-DPARADIGM_CORE_EXECUTABLE=true"
  - cd /home/travis/build/JessyDL/paradigm/project_files/make/x64/
  - make .