language: cpp
compiler: clang
sudo: required
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

before_install:
  # Install a supported cmake version (>= 3.11)
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget -O cmake.sh https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh
  - chmod +x cmake.sh
  - ./cmake.sh --prefix=$HOME/usr --exclude-subdir --skip-license

  # Install Vulkan SDK
  - mkdir -p $TRAVIS_BUILD_DIR/../VulkanSDK
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - export VK_VERSION=1.1.82.1
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz -C $TRAVIS_BUILD_DIR/../VulkanSDK
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/../VulkanSDK/$VK_VERSION/x86_64
  - export CXX="clang++-6.0" CC="clang-6.0"
  - eval "${MATRIX_EVAL}"
  
  # Install libc++
  - cd $TRAVIS_BUILD_DIR/../
  - git clone --depth=1 https://github.com/llvm-mirror/llvm.git llvm-source
  - git clone --depth=1 https://github.com/llvm-mirror/libcxx.git llvm-source/projects/libcxx
  - git clone --depth=1 https://github.com/llvm-mirror/libcxxabi.git llvm-source/projects/libcxxabi
  
  - mkdir llvm-build && cd llvm-build
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DLIBCXX_ABI_UNSTABLE=ON -DLLVM_USE_SANITIZER=${LIBCXX_SANITIZER} -DLLVM_BUILD_32_BITS=OFF ../llvm-source
  - make cxx -j2
  - sudo make install-cxxabi install-cxx
  
  - cd $TRAVIS_BUILD_DIR
  

script:
  - bash build.sh -VULKAN_VERSION 1.1.82.1 -VULKAN_ROOT $TRAVIS_BUILD_DIR/../VulkanSDK -COMPILER CLang -G Make -cmake_params "-DPARADIGM_CORE_EXECUTABLE=true"
  - cd $TRAVIS_BUILD_DIR/project_files/make/x64/
  - make