var hierarchy =
[
    [ "memory::allocator_base", "classmemory_1_1allocator__base.html", [
      [ "memory::block_allocator", "classmemory_1_1block__allocator.html", null ],
      [ "memory::default_allocator", "classmemory_1_1default__allocator.html", null ]
    ] ],
    [ "core::data::framebuffer::attachment", "classcore_1_1data_1_1framebuffer_1_1attachment.html", null ],
    [ "core::gfx::framebuffer::attachment", "structcore_1_1gfx_1_1framebuffer_1_1attachment.html", null ],
    [ "core::meta::shader::vertex::attribute", "classcore_1_1meta_1_1shader_1_1vertex_1_1attribute.html", null ],
    [ "core::meta::shader::vertex::binding", "classcore_1_1meta_1_1shader_1_1vertex_1_1binding.html", null ],
    [ "core::gfx::framebuffer::binding", "structcore_1_1gfx_1_1framebuffer_1_1binding.html", null ],
    [ "core::data::material::blendstate", "classcore_1_1data_1_1material_1_1blendstate.html", null ],
    [ "core::data::buffer", "classcore_1_1data_1_1buffer.html", null ],
    [ "core::gfx::buffer", "classcore_1_1gfx_1_1buffer.html", null ],
    [ "core::resource::cache", "classcore_1_1resource_1_1cache.html", null ],
    [ "core::ecs::command_buffer", "classcore_1_1ecs_1_1command__buffer.html", null ],
    [ "core::gfx::buffer::commit_instruction", "structcore_1_1gfx_1_1buffer_1_1commit__instruction.html", null ],
    [ "core::data::geometry::constants", "structcore_1_1data_1_1geometry_1_1constants.html", null ],
    [ "core::gfx::context", "classcore_1_1gfx_1_1context.html", null ],
    [ "utility::debug", "classutility_1_1debug.html", null ],
    [ "core::data::framebuffer::attachment::description", "classcore_1_1data_1_1framebuffer_1_1attachment_1_1description.html", null ],
    [ "utility::platform::directory", "classutility_1_1platform_1_1directory.html", null ],
    [ "core::gfx::drawgroup", "classcore_1_1gfx_1_1drawgroup.html", null ],
    [ "core::meta::shader::instance::element", "classcore_1_1meta_1_1shader_1_1instance_1_1element.html", null ],
    [ "core::ecs::entity", "structcore_1_1ecs_1_1entity.html", null ],
    [ "core::ecs::except< Ts >", "structcore_1_1ecs_1_1except.html", null ],
    [ "psl::meta::file", "classpsl_1_1meta_1_1file.html", [
      [ "core::meta::shader", "classcore_1_1meta_1_1shader.html", null ],
      [ "core::meta::texture", "classcore_1_1meta_1_1texture.html", null ]
    ] ],
    [ "core::ecs::filter< Ts >", "structcore_1_1ecs_1_1filter.html", null ],
    [ "core::data::framebuffer", "classcore_1_1data_1_1framebuffer.html", null ],
    [ "core::gfx::framebuffer", "classcore_1_1gfx_1_1framebuffer.html", null ],
    [ "core::data::geometry", "classcore_1_1data_1_1geometry.html", null ],
    [ "core::gfx::geometry", "classcore_1_1gfx_1_1geometry.html", null ],
    [ "core::resource::handle< T >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::core::gfx::buffer >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::core::gfx::framebuffer >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::core::gfx::geometry >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::core::gfx::material >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::core::gfx::sampler >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::buffer >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::context >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::buffer >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::context >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::framebuffer >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::geometry >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::material >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::pipeline >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::pipeline_cache >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::sampler >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::shader >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::swapchain >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::core::gfx::texture >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::swapchain >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::os::surface >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< data::window >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::systems::input", "classcore_1_1systems_1_1input.html", null ],
    [ "core::meta::shader::instance", "classcore_1_1meta_1_1shader_1_1instance.html", null ],
    [ "psl::meta::library", "classpsl_1_1meta_1_1library.html", null ],
    [ "core::gfx::material", "classcore_1_1gfx_1_1material.html", null ],
    [ "core::data::material", "classcore_1_1data_1_1material.html", null ],
    [ "core::ecs::details::mf_post_tick< T, std::void_t< decltype(std::declval< T & >().post_tick(std::declval< core::ecs::command_buffer & >()))> >", "structcore_1_1ecs_1_1details_1_1mf__post__tick_3_01_t_00_01std_1_1void__t_3_01decltype_07std_1_13b7822da8f3d30be8ad5528af15910ca.html", null ],
    [ "core::ecs::details::mf_pre_tick< T, std::void_t< decltype(std::declval< T & >().pre_tick(std::declval< core::ecs::command_buffer & >()))> >", "structcore_1_1ecs_1_1details_1_1mf__pre__tick_3_01_t_00_01std_1_1void__t_3_01decltype_07std_1_1d840898bfbf0154639315df694280199e.html", null ],
    [ "core::systems::input::mouse_coordinate", "structcore_1_1systems_1_1input_1_1mouse__coordinate.html", null ],
    [ "core::systems::input::mouse_delta", "structcore_1_1systems_1_1input_1_1mouse__delta.html", null ],
    [ "core::ecs::on_add< Ts >", "structcore_1_1ecs_1_1on__add.html", null ],
    [ "core::ecs::on_break< Ts >", "structcore_1_1ecs_1_1on__break.html", null ],
    [ "core::ecs::on_combine< Ts >", "structcore_1_1ecs_1_1on__combine.html", null ],
    [ "core::ecs::on_remove< Ts >", "structcore_1_1ecs_1_1on__remove.html", null ],
    [ "utility::platform::os", "classutility_1_1platform_1_1os.html", null ],
    [ "core::ecs::pack< Ts >", "classcore_1_1ecs_1_1pack.html", null ],
    [ "core::gfx::pass", "classcore_1_1gfx_1_1pass.html", null ],
    [ "core::gfx::pipeline", "classcore_1_1gfx_1_1pipeline.html", null ],
    [ "core::gfx::pipeline_cache", "classcore_1_1gfx_1_1pipeline__cache.html", null ],
    [ "core::gfx::pipeline_key", "structcore_1_1gfx_1_1pipeline__key.html", null ],
    [ "psl::serialization::polymorphic< T >", "classpsl_1_1serialization_1_1polymorphic.html", null ],
    [ "psl::serialization::property< T, Char >", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"ANISOTROPY\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"COMPARE\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"DEPTH_TEST\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"DEPTH_WRITE\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"ENABLED\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"MIPMAPS\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"NORMALIZED_COORDINATES\", 22)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"SHARED\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< bool, const_str(\"WIREFRAME_MODE\", 14)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< core::data::framebuffer::attachment::description, const_str(\"DESCRIPTION\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< core::gfx::buffering, const_str(\"BUFFERING\", 9)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< core::gfx::surface_mode, const_str(\"MODE\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< float, const_str(\"MAX_ANISO\", 9)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< float, const_str(\"MIP_BIAS\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< float, const_str(\"MIP_MAX\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< float, const_str(\"MIP_MIN\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< int, const_str(\"PRIORITY\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::psl::UID, const_str(\"psl::UID\", 3)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::string8_t, const_str(\"BUFFER\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::string8_t, const_str(\"NAME\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::UID, const_str(\"SAMPLER\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::UID, const_str(\"SHADER\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< psl::UID, const_str(\"TEXTURE UID\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::unordered_map< psl::string, core::core::stream >, const_str(\"STREAMS\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< binding >, const_str(\"BINDINGS\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::data::framebuffer::attachment >, const_str(\"ATTACHMENTS\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::data::material::blendstate >, const_str(\"BLEND_STATES\", 12)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::meta::shader::instance::element >, const_str(\"ELEMENTS\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::meta::shader::instance::element >, const_str(\"SUB_ELEMENTS\", 12)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::meta::shader::vertex::attribute >, const_str(\"ATTRIBUTES\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< core::meta::shader::vertex::binding >, const_str(\"VERTEX_BINDINGS\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< descriptor >, const_str(\"DESCRIPTORS\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< float >, const_str(\"DATA\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< index_size_t >, const_str(\"INDICES\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< psl::string8_t >, const_str(\"DEFINES\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< psl::string8_t >, const_str(\"TAGS\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< stage >, const_str(\"STAGES\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< std::vector< uint8_t >, const_str(\"DEFAULT\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< type, const_str(\"TYPE\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"BINDING\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"DEPTH\", 5)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"FRAMEBUFFER COUNT\", 17)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"HEIGHT\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"LAYERS\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"LOCATION\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"MIP_LEVELS\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"OFFSET\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"SIZE\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< uint32_t, const_str(\"WIDTH\", 5)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::AttachmentLoadOp, const_str(\"LOAD_OP\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::AttachmentLoadOp, const_str(\"STENCIl_LOAD_OP\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::AttachmentStoreOp, const_str(\"STENCIl_STORE_OP\", 16)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::AttachmentStoreOp, const_str(\"STORE_OP\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendFactor, const_str(\"ALPHA_BLEND_DST\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendFactor, const_str(\"ALPHA_BLEND_SRC\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendFactor, const_str(\"COLOR_BLEND_DST\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendFactor, const_str(\"COLOR_BLEND_SRC\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendOp, const_str(\"ALPHA_BLEND_OP\", 14)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BlendOp, const_str(\"COLOR_BLEND_OP\", 14)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BorderColor, const_str(\"BORDER_COLOR\", 12)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::BufferUsageFlags, const_str(\"USAGE\", 5)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ClearValue, const_str(\"CLEAR VALUE\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ColorComponentFlags, const_str(\"COMPONENT_FLAGS\", 15)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::CompareOp, const_str(\"COMPARE_OPERATION\", 17)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::CompareOp, const_str(\"DEPTH_COMPARE\", 13)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::CullModeFlagBits, const_str(\"CULLING\", 7)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::DescriptorType, const_str(\"DESCRIPTOR\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::DescriptorType, const_str(\"TYPE\", 4)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::Filter, const_str(\"FILTER_MAX\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::Filter, const_str(\"FILTER_MIN\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::Format, const_str(\"FORMAT\", 6)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ImageAspectFlags, const_str(\"ASPECT_MASK\", 11)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ImageLayout, const_str(\"FINAL_LAYOUT\", 12)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ImageLayout, const_str(\"INITIAL_LAYOUT\", 14)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ImageUsageFlags, const_str(\"USAGE\", 5)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ImageViewType, const_str(\"IMAGE_TYPE\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::MemoryPropertyFlags, const_str(\"PROPERTIES\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::SampleCountFlagBits, const_str(\"SAMPLE_COUNT_FLAGS\", 18)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::SamplerAddressMode, const_str(\"ADDRESS_U\", 9)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::SamplerAddressMode, const_str(\"ADDRESS_V\", 9)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::SamplerAddressMode, const_str(\"ADDRESS_W\", 9)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::SamplerMipmapMode, const_str(\"MIP_MODE\", 8)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::ShaderStageFlags, const_str(\"STAGE\", 5)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "psl::serialization::property< vk::VertexInputRate, const_str(\"INPUT_RATE\", 10)>", "structpsl_1_1serialization_1_1property.html", null ],
    [ "memory::range", "classmemory_1_1range.html", null ],
    [ "core::ecs::range< T >", "classcore_1_1ecs_1_1range.html", null ],
    [ "memory::region", "classmemory_1_1region.html", null ],
    [ "core::data::sampler", "classcore_1_1data_1_1sampler.html", null ],
    [ "core::gfx::sampler", "classcore_1_1gfx_1_1sampler.html", null ],
    [ "core::systems::input::scroll_delta", "structcore_1_1systems_1_1input_1_1scroll__delta.html", null ],
    [ "memory::segment", "classmemory_1_1segment.html", null ],
    [ "core::gfx::shader", "classcore_1_1gfx_1_1shader.html", null ],
    [ "core::gfx::shader::specialization", "structcore_1_1gfx_1_1shader_1_1specialization.html", null ],
    [ "core::stream", "classcore_1_1stream.html", null ],
    [ "core::os::surface", "classcore_1_1os_1_1surface.html", null ],
    [ "core::gfx::swapchain", "classcore_1_1gfx_1_1swapchain.html", null ],
    [ "core::gfx::texture", "classcore_1_1gfx_1_1texture.html", null ],
    [ "utility::debug::trace_info", "structutility_1_1debug_1_1trace__info.html", null ],
    [ "psl::UID", "structpsl_1_1_u_i_d.html", null ],
    [ "core::meta::shader::vertex", "classcore_1_1meta_1_1shader_1_1vertex.html", null ],
    [ "core::data::window", "classcore_1_1data_1_1window.html", null ]
];