FROM nebumind/ubuntu-clang8

ENV CLANG_VERSION=8
ENV	CMAKE_VERSION="3.13"
ENV	CMAKE_PATCH="3"
ENV CLANG_VERSION="8"
ENV EXTRA_CMAKE_PARAMS="-DPE_MODE=LIB"
ENV DOXGEN=false
ENV CORE_COUNT=12
ENV BUILD_TYPE=Release

# misc tools
RUN apt-get update && \
	apt-get install -y ca-certificates && \
	apt-get install -y --no-install-recommends apt-utils \
	wget \
	git \
	tofrodos

RUN DEBIAN_FRONTEND=noninteractive apt install -y tzdata

#documentation tools 
RUN apt-get update && \
	apt-get install doxygen -y \
	doxygen-latex \
	graphviz
		
#graphics libraries
RUN apt-get update && \
	apt-get install libx11-dev -y \
	libx11-xcb-dev \
	libxrandr-dev
	
#paradigm toolset dependencies
RUN apt-get update && apt-get install python3 -y
	
# purge cmake, we will install a later version
RUN apt-get update && \
	apt-get remove --purge -y cmake && \
	apt-get autoremove -y && apt-get autoclean -y && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*
	
WORKDIR /
# cmake
RUN mkdir /cmake && \
	cd /cmake  && \
	wget https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_PATCH}-Linux-x86_64.tar.gz && \
	tar xf cmake-${CMAKE_VERSION}.${CMAKE_PATCH}-Linux-x86_64.tar.gz
	
ENV PATH=${PATH}:/cmake/cmake-${CMAKE_VERSION}.${CMAKE_PATCH}-Linux-x86_64/bin

CMD [ "/bin/bash" ]
WORKDIR /
	
RUN apt-get update && \
  apt-get install -y rsync \
	clang-tools-${CLANG_VERSION} \
	clang-format-${CLANG_VERSION} \
	clang-tidy-${CLANG_VERSION} \
	iwyu \
	cppcheck
	
COPY scripts /
RUN chmod +x /install.sh && \
	chmod +x /clone.sh  && \
	chmod +x /clone_local.sh  && \
	chmod +x /copy.sh
	
RUN fromdos clone.sh && fromdos install.sh && fromdos clone_local.sh && fromdos copy.sh
	
ENV py=python3
ENV python=python3
ENV CXX=clang++-8
ENV CC=clang-8

CMD ["/bin/bash"]