FROM mcr.microsoft.com/windows/servercore:ltsc2019_amd64

ENV	CMAKE_VERSION="3.13"
ENV	CMAKE_PATCH="3"
ENV	VSBUILDTOOLS="15.9.4.0"
ENV	VK_VERSION="1.1.82.1"
ENV EXTRA_CMAKE_PARAMS="-DPE_MODE=LIB"
ENV DOXGEN=false
ENV CORE_COUNT=6
ENV BUILD_TYPE=Release

# Download the tools 
SHELL ["cmd", "/S", "/C"]
ADD "https://aka.ms/vs/15/release/vs_community.exe" "C:\TEMP\vs_community.exe"
ADD "https://dist.nuget.org/win-x86-commandline/v4.7.0/nuget.exe" "C:\TEMP\nuget.exe"


# Install VS 2017 community 
RUN C:\TEMP\vs_community.exe --includeRecommended --includeOptional --quiet --nocache --norestart --wait \
    --add Microsoft.VisualStudio.Workload.Azure \
    --add Microsoft.VisualStudio.Workload.ManagedDesktop \
    --add Microsoft.VisualStudio.Workload.NetCoreTools \
    --add Microsoft.VisualStudio.Workload.NetWeb \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0


# Install Chocolatey
ENV chocolateyUseWindowsCompression = false

SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); \
    [System.Environment]::SetEnvironmentVariable('PATH', "\"${env:PATH};%ALLUSERSPROFILE%\chocolatey\bin\"", 'Machine'); \
    choco feature enable -n allowGlobalConfirmation;

# Install git tools with chocolatey
RUN choco install git -y \
    git-lfs -y \
    git-credential-manager-for-windows -y \
		choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System' \
    choco install -y python3

# install vulkan
WORKDIR VulkanSDK
RUN git clone https://github.com/KhronosGroup/Vulkan-Headers.git Vulkan-Headers; \
	cd Vulkan-Headers; \
	git checkout c4e056d365472174471a243dfefbfe66a03564af; \
	cd .. ; \
	git clone https://github.com/KhronosGroup/Vulkan-Hpp.git Vulkan-Hpp; \
	cd Vulkan-Hpp; \
  git checkout 7e701c79d6998260712dc6578732d534871f0f8a; \
	cd .. ; \
	mkdir -p "$Env:VK_VERSION/Include/vulkan/"; \
	Copy-Item -Path Vulkan-Headers/include/vulkan -Recurse -Destination "$Env:VK_VERSION/Include/vulkan/" -Container -Force; \
	Copy-Item -Path Vulkan-Hpp/vulkan -Recurse -Destination "$Env:VK_VERSION/Include/vulkan/" -Container -Force

ENV VULKAN_ROOT_DIR="C:/VulkanSDK"
ENV VULKAN_SDK="$Env:VULKAN_ROOT_DIR/$Env:VK_VERSION/"

WORKDIR /
COPY scripts /

# Launch VS2017 developer command prompt when started
SHELL ["cmd", "/S", "/C"]
ENTRYPOINT [ "CMD", "/k", "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools/VsDevCmd.bat" ]