name: android

on: [push]
    
jobs:
  build:
    env:
      CC: gcc
      CXX: g++
    strategy:
      fail-fast: false
      matrix:
        graphics: [vulkan]
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: dependencies
      run: yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses
    - name: initialize
      run: cmake --preset=android-release-${{ matrix.graphics }}
    - name: compile
      run: cmake --build --preset=android-release-${{ matrix.graphics }}
    - name: verify
      run: python3 -c "import os;import sys;sys.exit(0) if os.path.exists('builds/android/main/build/outputs/bundle/release/main-release.aab') else sys.exit(1)"
