name: documentation

on:
  push:
    branches:
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: ParadigmEngine/ParadigmEngine.github.io
        path: documentation
        token: ${{secrets.PUSH_TOKEN}}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Doxygen
      run: sudo apt-get update && sudo apt-get install doxygen
    - name: Setup m.css
      run: git clone https://github.com/JessyDL/m.css.git mcss --depth 1    
    - name: Update Python
      run: pip3 install jinja2 Pygments
    - name: Generate
      run: |
        git_tag=`git name-rev --name-only --tags HEAD | sed 's/^undefined$/develop/'`
        rm -rf documentation/${git_tag}
        python mcss/documentation/doxygen.py tools/doxyfile --output-dir documentation/${git_tag}
    - name: Publish
      run: |
        git_tag=`git name-rev --name-only --tags HEAD | sed 's/^undefined$/develop/'`
        cd documentation
        git config --local user.name "$USERNAME"
        git config --local user.email "41898282+$USERNAME@users.noreply.github.com"
        git diff --exit-code --quiet || (git add -A && git commit -m "Documentation update for '${git_tag}'" && git push https://$USERNAME:$REPO_KEY@github.com/ParadigmEngine/ParadigmEngine.github.io.git)
      env:
        REPO_KEY: ${{secrets.PUSH_TOKEN}}
        USERNAME: github-actions[bot]