name: build-test

on: [push]

jobs:
  windows:
    name: build windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: initialize
      run: python3 build.py --cmake_params="-DPE_MODE=LIB"        
    - name: build
      run: |
        cd project_files/*/*
        cmake -–build . –config Release
        
