name: paradigm

on: [push]
    
jobs:      
  windows:
    strategy:
      fail-fast: false
      matrix:
        graphics: [vulkan, all]
    name: windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: setup dependencies
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: initialize
      run: |
            python3 tools/generate_project_info.py
            cmake --preset=windows-${{ matrix.graphics }} -DPE_BENCHMARKS=ON
            python3 tools/patch.py ./project_files/x64/
    - name: compile
      run: cmake --build --preset=windows-release-${{ matrix.graphics }}
    - name: test
      run: |
            cd builds\x64\release\bin
            .\tests.exe --formatter compact --no-source
    - name: benchmark
      run: |
           cd builds\x64\release\bin
           .\benchmarks.exe --benchmark_out_format=json --benchmark_out=results.json
    - name: finalize
      uses: actions/upload-artifact@v2
      with:
        name: windows-${{ matrix.graphics }}
        path: builds/x64/release/bin/results.json
        if-no-files-found: error
  ubuntu:
    container:
      image: gcc:11.2.0
    strategy:
      fail-fast: false
      matrix:
        graphics: [vulkan]
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: setup dependencies
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.sh -q -O /tmp/cmake-install.sh \
        && chmod u+x /tmp/cmake-install.sh \
        && mkdir /opt/cmake \
        && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake \
        && rm /tmp/cmake-install.sh
        ln -s /opt/cmake/bin/* /usr/bin/
        apt-get update && apt-get install python3 -y
        python3 tools/generate_project_info.py
    - name: initialize
      run: cmake --preset=gnu-linux-release-${{ matrix.graphics }} -DPE_BENCHMARKS=ON
    - name: compile
      run: cmake --build --preset=gnu-linux-release-${{ matrix.graphics }}
    - name: test
      run: ./builds/*/bin/tests --formatter compact --no-source
    - name: benchmark
      run: |
           cd builds/*/bin
           ./benchmarks --benchmark_out_format=json --benchmark_out=results.json
    - name: finalize
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-${{ matrix.graphics }}
        path: builds/*/bin/results.json
        if-no-files-found: error
