name: ubuntu

on: 
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.py'
      - 'CMakeLists.txt'
      - .github/**

jobs:
  # fires off the documentation generator
  documentation:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PUSH_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'ParadigmEngine',
            repo: 'ParadigmEngine.github.io',
            workflow_id: 'documentation.yml',
            ref: 'main'
          })
  # build the project for the various permutations
  build:
    strategy:
      fail-fast: true
      matrix:
        target: [gnu-linux, android]
        compiler: [gcc, clang]
        graphics: [vulkan, all]
        include:
          - cc: gcc-11
            cxx: g++-11
            benchmarks: ON
            tests: ON
            compiler: gcc
            target: gnu-linux
          - cc: gcc-11
            cxx: g++-11
            benchmarks: OFF
            tests: OFF
            compiler: gcc
            target: android
          - cc: clang-14
            cxx: clang++-14
            benchmarks: OFF
            tests: OFF
            compiler: clang
        exclude:
          - target: android
            compiler: clang
          - target: android
            graphics: all
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: setup dependencies
      run: python3 tools/generate_project_info.py
    - name: install GL libraries
      if: ${{ matrix.graphics  == 'all' ||  matrix.graphics  == 'gles' }}
      run: sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev -y
    - name: dependencies
      if: ${{ matrix.target == 'android' }}
      run: yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses
    - name: initialize
      run: cmake --preset=${{ matrix.target }}-release-${{ matrix.graphics }} -DPE_BENCHMARKS=${{ matrix.benchmarks }} -DPE_TESTS=${{ matrix.tests }}
    - name: compile
      run: cmake --build --preset=${{ matrix.target }}-release-${{ matrix.graphics }}
    - name: test
      if: ${{ matrix.tests == 'ON' }}
      run: ./builds/default/bin/tests --formatter compact --no-source
    - name: finalize
      if: ${{ matrix.benchmarks == 'ON' }}
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{ matrix.compiler }}-${{ matrix.graphics }}-bin
        path: builds/default/bin/benchmarks
        if-no-files-found: error
        retention-days: 1
    - name: verify
      if: ${{ matrix.target == 'android' }}
      run: python3 -c "import os;import sys;sys.exit(0) if os.path.exists('builds/android/main/build/outputs/bundle/release/main-release.aab') else sys.exit(1)"
  # run benchmarks for the permutations that build the benchmarks binary
  benchmark:
    strategy:
      fail-fast: true
      matrix:
        graphics: [vulkan, all]
        include:
          - compiler: gcc
    name: benchmark
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: setup
      id: download
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-${{ matrix.compiler }}-${{ matrix.graphics }}-bin
    - name: install GL libraries
      if: ${{ matrix.graphics  == 'all' ||  matrix.graphics  == 'gles' }}
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev -y
    - name: prepare
      run: chmod +x benchmarks
    - name: benchmark
      run: ./benchmarks --benchmark_out_format=json --benchmark_out=results.json
    - name: finalize
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{ matrix.COMPILER }}-${{ matrix.graphics }}
        path: results.json
        if-no-files-found: error
