name: ubuntu

on: [push]
    
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        graphics: [vulkan, all]
        include:
          - CC: gcc-11
            CXX: g++-11
            BENCHMARKS: ON
            TESTS: ON
            COMPILER: gcc
          - CC: clang-14
            CXX: clang++-14
            BENCHMARKS: OFF
            TESTS: OFF
            COMPILER: clang
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: setup dependencies
      run: python3 tools/generate_project_info.py
    - name: install GL libraries
      if: ${{ matrix.graphics  == 'all' ||  matrix.graphics  == 'gles' }}
      run: sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev -y
    - name: initialize
      run: cmake --preset=gnu-linux-release-${{ matrix.graphics }} -DPE_BENCHMARKS=${{ matrix.BENCHMARKS }} -DPE_TESTS=${{ matrix.TESTS }}
    - name: compile
      run: cmake --build --preset=gnu-linux-release-${{ matrix.graphics }}
    - name: test
      if: ${{ matrix.TESTS == 'ON' }}
      run: ./builds/default/bin/tests --formatter compact --no-source
    - name: finalize
      if: ${{ matrix.BENCHMARKS == 'ON' }}
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{ matrix.COMPILER }}-${{ matrix.graphics }}-bin
        path: builds/default/bin/benchmarks
        if-no-files-found: error
        retention-days: 1
  benchmark:
    strategy:
      fail-fast: true
      matrix:
        graphics: [vulkan, all]
        include:
          - CC: gcc-11
            CXX: g++-11
            BENCHMARKS: ON
            TESTS: ON
            COMPILER: gcc
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    name: benchmark
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: setup
      id: download
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-${{ matrix.COMPILER }}-${{ matrix.graphics }}-bin
    - name: install GL libraries
      if: ${{ matrix.graphics  == 'all' ||  matrix.graphics  == 'gles' }}
      run: sudo apt-get update && apt-get install libgl1-mesa-dev libegl1-mesa-dev -y
    - name: prepare
      run: chmod +x benchmarks
    - name: benchmark
      run: ./benchmarks --benchmark_out_format=json --benchmark_out=results.json
    - name: finalize
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{ matrix.COMPILER }}-${{ matrix.graphics }}
        path: results.json
        if-no-files-found: error
