name: windows

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        graphics: [vulkan, all]
        include:
          - benchmarks: OFF
          - graphics: all
            benchmarks: ON
    name: build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive    
    - uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: setup dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: initialize
      run: |
            python3 tools/generate_project_info.py
            cmake --preset=windows-release-${{ matrix.graphics }} -DPE_BENCHMARKS=${{ matrix.benchmarks }}
            python3 tools/patch.py --project ./project_files/x64/
    - name: compile
      run: cmake --build --preset=windows-release-${{ matrix.graphics }} -j ${{ steps.cpu-cores.outputs.count }}
    - name: test
      run: |
            cd builds\x64\release\bin
            .\tests.exe --formatter compact --no-source --single-threaded
    - name: finalize    
      if: ${{ matrix.benchmarks == 'ON' }}
      uses: actions/upload-artifact@v3
      with:
        name: windows-${{ matrix.graphics }}-bin
        path: builds/x64/release/bin/benchmarks.exe
        if-no-files-found: error
        retention-days: 1
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        graphics: [ all ]
    name: benchmark
    needs: build
    runs-on: windows-2022
    steps:
    - name: setup
      id: download
      uses: actions/download-artifact@v3
      with:
        name: windows-${{ matrix.graphics }}-bin
    - name: benchmark
      run: .\benchmarks.exe --benchmark_out_format=json --benchmark_out=results.json
    - name: finalize
      uses: actions/upload-artifact@v3
      with:
        name: windows-${{ matrix.graphics }}
        path: results.json
        if-no-files-found: error
